---
title: "masters"
author: "Cody Frisby"
date: "1/5/2017"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.align = 'center', dpi=200,warning=F,message=F, eval = F)
```

## Reading and reducing the data  

```{r}
df <- read.csv("~/Documents/masters/data/dat.csv")
# need the SG variables to be numeric...
#df2 <- read.csv("~/Documents/masters/m83to16.csv")
library(data.table); library(dplyr)
df <- data.table(df)
# subsetting the data while creating a new column that sums the scores.
df.score <- df[, list(score = sum(Score, na.rm = TRUE), 
                      freq = .N), 
          by = c("Tournament.Year", "Player.Name",
                 "SG..Approach.the.Green",
                 "SG..Around.the.Green", "SG..Off.the.Tee",
                 "SG..Putting", "SG..Total")]
# renaming variables for ease
names(df.score) <- c("year", "player", "sg.approach", "sg.around",
                     "sg.tee", "sg.putt", "sg.total", "score",
                     "holes")
# there are some obs with only 18 holes played...
df.score <- df.score[df.score$holes >= 36, ]
# there is one observation with 54 holes played :(
df.score <- df.score[df.score$holes != 54, ]
# adding the mean round score
df.score$score.ave <- ifelse(df.score$holes == 72,
                             df.score$score/4, df.score$score/2)
# removing obs where sg.total = 0 and NAs
df.score <- df.score[df.score$sg.total != 0, ]
df.score <- df.score[!is.na(df.score$sg.total), ]
# remove Arnold Palmer
df.score <- df.score[!(df.score$player %in% "Palmer, Arnold"), ]
df.removed <- df[!(df$Player.Name %in% df.score$player), ]
temp <- df.removed[, list(freq = .N), by = c("Player.Name",
                                             "Tournament.Year")]
# need to create some new variables...like rank and such...
library(plyr)
df.ranks <- ddply(df.score, .(year), transform, 
                  rank = rank(score.ave, ties.method = "min"))
# done getting ranks by year...there are ties for first when there
# was a playoff.
##### get the number of masters played each years by each player############
# data only goes back to 1984 so if a player played prior to that
#year their total masters played will NOT be accurate. 
df1 <- read.csv("~/Documents/masters/data/m83to16.csv")
df1 <- data.table(df1)
df1.freq <- df1[, list(score = sum(Score, na.rm = TRUE), 
                       freq = .N), by = 
                  c("Tournament.Year", "Player.Name")]
df1.freq$dummy <- 1
# sort the data frame by year so we can count up.
df1.freq <- df1.freq[order(df1.freq$Tournament.Year), ]
df1.freq$masters <- ave(df1.freq$dummy, df1.freq$Player.Name, FUN=cumsum)
df1.freq <- df1.freq[, c(1,2,6), with = FALSE]
names(df1.freq) <- c("year", "player", "masters") # create same column names
##### done getting the number of masters played by each player
df.final <- merge(df.ranks, df1.freq, by = c("year", "player"))
```

## GGally scatterplot  

```{r}
# scatter plot matrix
library(ggplot2); library(GGally)
#ggpairs(df.final[, c(3:6, 10, 11, 12)]) # this is a slow plot
```

## Create new catagorical variables for SG catagories  

```{r}
f <- function(x){(x - mean(x))/sd(x)} # normal score function
# try to bin the SG variables:
# sg.total
library(dplyr)
df.final2 <- df.final %>% 
  group_by(year) %>% 
  mutate(z.score = f(sg.total))
z.score <- df.final2$z.score
group.z <- factor(ifelse(z.score >= 2, 1, 
                  ifelse(z.score < 2 & z.score >= 1, 2, 
                  ifelse(z.score < 1 & z.score >= 0, 3,
                  ifelse(z.score < 0 & z.score >= -1, 4,
                  ifelse(z.score < -1 & z.score >= -2, 5, 6)
                  )))))
df.final$total.z <- group.z # sg.total binning complete.
# sg.approach
df.final2 <- df.final %>% 
  group_by(year) %>% 
  mutate(z.score = f(sg.approach))
z.score <- df.final2$z.score
group.z <- factor(ifelse(z.score >= 2, 1, 
                  ifelse(z.score < 2 & z.score >= 1, 2, 
                  ifelse(z.score < 1 & z.score >= 0, 3,
                  ifelse(z.score < 0 & z.score >= -1, 4,
                  ifelse(z.score < -1 & z.score >= -2, 5, 6)
                  )))))
df.final$approach.z <- group.z
# sg.around
df.final2 <- df.final %>% 
  group_by(year) %>% 
  mutate(z.score = f(sg.around))
z.score <- df.final2$z.score
group.z <- factor(ifelse(z.score >= 2, 1, 
                  ifelse(z.score < 2 & z.score >= 1, 2, 
                  ifelse(z.score < 1 & z.score >= 0, 3,
                  ifelse(z.score < 0 & z.score >= -1, 4,
                  ifelse(z.score < -1 & z.score >= -2, 5, 6)
                  )))))
df.final$around.z <- group.z
# sg.tee
df.final2 <- df.final %>% 
  group_by(year) %>% 
  mutate(z.score = f(sg.tee))
z.score <- df.final2$z.score
group.z <- factor(ifelse(z.score >= 2, 1, 
                  ifelse(z.score < 2 & z.score >= 1, 2, 
                  ifelse(z.score < 1 & z.score >= 0, 3,
                  ifelse(z.score < 0 & z.score >= -1, 4,
                  ifelse(z.score < -1 & z.score >= -2, 5, 6)
                  )))))
df.final$tee.z <- group.z
# sg.putt
df.final2 <- df.final %>% 
  group_by(year) %>% 
  mutate(z.score = f(sg.putt))
z.score <- df.final2$z.score
group.z <- factor(ifelse(z.score >= 2, 1, 
                  ifelse(z.score < 2 & z.score >= 1, 2, 
                  ifelse(z.score < 1 & z.score >= 0, 3,
                  ifelse(z.score < 0 & z.score >= -1, 4,
                  ifelse(z.score < -1 & z.score >= -2, 5, 6)
                  )))))
df.final$putt.z <- group.z
rm(df.final2)
# updating the original data frame with all the holes data.
df <- df[df$SG..Total != 0, ]
df <- df[!is.na(df$SG..Total), ]
df <- df[!(df$Player.Name %in% "Palmer, Arnold"), ]
names(df)[c(1, 3)] <- c("year", "player")
df <- df[ ,(c(2, 4, 19:23)) := NULL]
df <- merge(df, df.final, by = c("year", "player"), all.x = TRUE)
df <- df[complete.cases(df), ]
rm(df.ranks); rm(df.score); rm(df1); rm(df1.freq)
```

## ggplot scatterplot  

```{r}
g <- ggplot(data = df.final, aes(x = rank, y = score.ave))
g <- g + geom_point(aes(colour = factor(holes)))
g
```



